ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDgH+AYnFRlUKAnQ7sJmj52l4hX0kHCMKXHd1+NZ8Cxt1pDd5fw0zGmaG5dPFz63Zz8NzAF8bXr6JoMKUfDsLoJVMdoMUsJ32ojqGR064mqxlXoJ3tvqnvC3HdQUB2bhyESdf9c3iEQ6TdztlSmnMOTVBWiM471h80YUVyxcYTffdrTo6nRboqmVRSdaSEZ4ylbjh+r2DHi22KMQ7ZggXFVfXMLE2IN10lwWC7RcHSS+secXfk6jBaUXLsrEW0tA8F7Ng9i5W4PTia/V1/VuUqaEV/xx5DW/ntql+ZaNBaFxnY5JPnY6AU8CWtEiDypBW+Rd0jDpvDatL7fNJkiA9VeJe46J03j0AkiuqStg/QL4lgUwukvfm0mlmRasUJxjPlDiiMg/FpslyStFPmHi97/nExIATrQXlKtibGhYGfaKq1YyEKq2SejCdanee3tzOJJoJ087Hk1WoWsuPiSltORvZGemuJ0TtR0S5hLNi0rs7hqSVK4nw2j3SL2eIm6F/k=

k3os:
  password: rancher
